version: "3.9"

services:
  user-profile-service:
    build: .
    env_file:
      - .env
    ports:
      - "3002:3002"
    depends_on:
      user-profile-db:
        condition: service_healthy
    restart: on-failure
    environment:
      - PYTHONUNBUFFERED=1
    networks:
      - nutrigym-network

  user-profile-db:
    image: postgres:15
    environment:
      POSTGRES_DB: user_profile_db
      POSTGRES_USER: user_profile_user
      POSTGRES_PASSWORD: user_profile_pass
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U user_profile_user -d user_profile_db"]
      interval: 5s
      timeout: 5s
      retries: 5
      start_period: 10s
    volumes:
      - postgres_data:/var/lib/postgresql/data
    networks:
      - nutrigym-network

volumes:
  postgres_data:

networks:
  nutrigym-network:
    external: true
