services:
  mongo:
    image: mongo:7.0
    container_name: ai-generator-mongo
    ports:
      - "27018:27017"
    networks:
      - nutrigym-network

  ai-generator-service:
    build: .
    container_name: ai-generator-service
    ports:
      - "3006:3006"
    env_file: .env
    depends_on:
      - mongo
    networks:
      - nutrigym-network
    command: uvicorn main:app --host 0.0.0.0 --port 3006

networks:
  nutrigym-network:
    external: true
