sonar.projectKey=g3-NutriGym
sonar.projectName=NutriGym

# Código fuente
sonar.sources=services

# Pruebas
sonar.tests=services
sonar.test.inclusions=**/tests/**

# Exclusiones
sonar.exclusions=**/__pycache__/**,\
**/.pytest_cache/**,\
**/venv/**,\
**/.venv/**,\
**/node_modules/**,\
**/htmlcov/**

# Cobertura
sonar.python.coverage.reportPaths=services/auth-service/coverage.xml

# Codificación
sonar.sourceEncoding=UTF-8