sonar.projectKey=g3-NutriGym
sonar.projectName=NutriGym
sonar.projectVersion=1.0

# Carpetas a analizar
sonar.sources=apps,services

# Carpetas a ignorar
sonar.exclusions=**/node_modules/**,\
**/.turbo/**,\
**/.venv/**,\
**/venv/**,\
**/__pycache__/**,\
**/dist/**,\
**/build/**,\
**/*.pyc

sonar.sourceEncoding=UTF-8

sonar.python.version=3.13