services:
  mosquitto:
    image: eclipse-mosquitto:2
    container_name: notification-mosquitto
    ports:
      - "1883:1883"
    volumes:
      - ./mosquitto.conf:/mosquitto/config/mosquitto.conf:ro
    networks:
      - nutrigym-network

  notification-service:
    build: .
    container_name: notification-service
    env_file: .env
    ports:
      - "3011:3011"
    depends_on:
      - mosquitto
    networks:
      - nutrigym-network

networks:
  nutrigym-network:
    external: true
