server {
  listen 80;
  server_name _;

  # FRONT: todo lo que no sea /api va al contenedor web
  location / {
    proxy_pass http://web:80;
    proxy_set_header Host $host;
    proxy_set_header X-Real-IP $remote_addr;
    proxy_set_header X-Forwarded-For $proxy_add_x_forwarded_for;
    proxy_set_header X-Forwarded-Proto $scheme;
  }

  # APIs
  location /api/auth/ { proxy_pass http://auth-service:3001/; proxy_set_header Host $host; }
  location /api/profile/ { proxy_pass http://user-profile-service:3002/; proxy_set_header Host $host; }
  location /api/authz/ { proxy_pass http://authorization-service:3003/; proxy_set_header Host $host; }

  location /api/nutrition/ {
    rewrite ^/api/nutrition/(.*)$ /$1 break;
    proxy_pass http://nutrition-form:3004;
    proxy_set_header Host $host;
  }

  location /api/plans/ { proxy_pass http://plan-management:3005/; proxy_set_header Host $host; }
  location /api/ai/ { proxy_pass http://ai-generator-service:3006/; proxy_set_header Host $host; }
}
