services:
  plan-management:
    build: .
    ports:
      - "3005:3005"
    env_file: .env
    depends_on:
      plan-postgres:
        condition: service_healthy
    networks:
      - nutrigym-network
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:3005/health"]
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 40s

  plan-postgres:
    image: postgres:15-alpine
    environment:
      POSTGRES_DB: nutrigym_plans
      POSTGRES_USER: user
      POSTGRES_PASSWORD: password
    ports:
      - "5433:5432"
    volumes:
      - plan_postgres_data:/var/lib/postgresql/data
    networks:
      - nutrigym-network
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U user -d nutrigym_plans"]
      interval: 10s
      timeout: 5s
      retries: 5
  
  rabbitmq:
    image: rabbitmq:3-management
    container_name: plan-rabbitmq
    ports:
      - "5673:5672"     # para que no choque con el global (si lo usas luego)
      - "15673:15672"
    networks:
      - nutrigym-network
      
  plan-redis:
    image: redis:7-alpine
    container_name: plan-redis

networks:
  nutrigym-network:
    external: true

volumes:
  plan_postgres_data:
