name: Auditoría de Seguridad - Dependency-Check

on:
  push:
    branches:
      - qa
      - main

  pull_request:
    branches:
      - qa
      - main

jobs:
  security-scan:

    runs-on: ubuntu-latest

    steps:

      - name: Checkout del código
        uses: actions/checkout@v4

      - name: Configurar Python
        uses: actions/setup-python@v5
        with:
          python-version: "3.13"

      - name: Actualizar pip
        run: |
          python -m pip install --upgrade pip

      - name: Buscar archivos requirements.txt
        run: |
          echo "=== Requirements encontrados ==="
          find services -name "requirements.txt"

      - name: Instalar dependencias de todos los microservicios
        run: |
          find services -name "requirements.txt" -exec pip install -r {} \;

      - name: Mostrar paquetes instalados
        run: |
          pip list

      - name: Ejecutar OWASP Dependency-Check
        id: dependency-check
        uses: dependency-check/Dependency-Check_Action@main
        continue-on-error: true

        with:
          project: "NutriGym"
          path: "."
          format: "HTML"
          out: "reports"

          args: >
            --enableExperimental
            --disableNodeAudit
            --disablePnpmAudit

      - name: Subir Reporte HTML
        uses: actions/upload-artifact@v4
        with:
          name: dependency-check-report
          path: reports/dependency-check-report.html